version: '2.3'

services:
  hw:
    image: ds_hw
    volumes:
      - /home/jiakun/classes/data_structure_2020_dec/:/data/jiakun
    mem_reservation: 2g
    env_file: .env
    entrypoint:
      - /bin/bash

  hw_notebook:
    image: ds_hw
    volumes:
      - /mnt/:/mnt/
      - /home/jiakun/code/dev/jiakundev:/data/jiakun
      - /home/jiakun/code/dev/jiakundev/jupyter:/notebooks
      - /home/jiakun/data/jiakundata:/data/jiakun/data
      - /home/jiakun/code/dev/stimuli:/data/stimuli
    ports:
      - 9999:8888
    env_file: .env



